<?php
/**
 * PIX Payment Block Template
 *
 * @package SicoobPayment
 */

if (!defined('ABSPATH')) {
    exit;
}

// Get PIX data from order
$pix_txid = $order->get_meta('_sicoob_pix_txid');
$pix_qrcode = $order->get_meta('_sicoob_pix_qrcode');
$pix_criacao = $order->get_meta('_sicoob_pix_criacao');
$pix_expiracao = $order->get_meta('_sicoob_pix_expiracao');

// Check if PIX data exists
if (empty($pix_qrcode)) {
    return;
}

// Check order status - only show PIX if order is pending payment
$order_status = $order->get_status();
$is_paid = $order->is_paid();

// Calculate expiration time
$expiration_time = $pix_criacao ? strtotime($pix_criacao) + $pix_expiracao : time() + 3600;
$time_remaining = max(0, $expiration_time - time());
$hours_remaining = floor($time_remaining / 3600);
$minutes_remaining = floor(($time_remaining % 3600) / 60);
?>

<div class="sicoob-pix-payment-block" id="sicoob-pix-payment-block" style="<?= $is_paid ? 'display: none;' : 'display: block;' ?>" data-order-id="<?php echo esc_attr($order->get_id()); ?>">
    <div class="sicoob-pix-header">
        <h3><?php _e('Pagamento via PIX', 'sicoob-payment'); ?></h3>
        <p><?php _e('Escaneie o QR Code ou copie o código PIX para realizar o pagamento', 'sicoob-payment'); ?></p>
    </div>

    <div class="sicoob-pix-content">
        <div class="sicoob-pix-left">
            <div class="sicoob-pix-qr-container">
                <div class="sicoob-pix-qr-code" data-qr-code="<?php echo esc_attr($pix_qrcode); ?>">
                    <!-- QR Code will be generated by JavaScript -->
                </div>
            </div>

            <div class="sicoob-pix-code-container">
                <input type="text" 
                       class="sicoob-pix-code-input" 
                       value="<?php echo esc_attr($pix_qrcode); ?>" 
                       readonly>
                <textarea class="sicoob-pix-code-textarea" 
                      readonly 
                      style="display: none;"><?php echo esc_textarea($pix_qrcode); ?></textarea>

                <button type="button" class="sicoob-pix-copy-btn">
                    <?php _e('Copiar', 'sicoob-payment'); ?>
                </button>

                <div class="sicoob-pix-info">
                    <p class="sicoob-pix-info-text">
                        <?php _e('O pagamento será identificado imediatamente após ser realizado e a página será atualizada', 'sicoob-payment'); ?>
                    </p>
                </div>
            </div>
        </div>

        <div class="sicoob-pix-right">
            <div class="sicoob-pix-instructions">
                <div class="sicoob-pix-step">
                    <div class="sicoob-pix-step-number">1</div>
                    <div class="sicoob-pix-step-content">
                        <h4 class="sicoob-pix-step-title"><?php _e('Abra o app do seu banco', 'sicoob-payment'); ?></h4>
                        <p class="sicoob-pix-step-text">
                            <?php _e('Acesse o aplicativo do seu banco no celular ou internet banking.', 'sicoob-payment'); ?>
                        </p>
                    </div>
                </div>

                <div class="sicoob-pix-step">
                    <div class="sicoob-pix-step-number">2</div>
                    <div class="sicoob-pix-step-content">
                        <h4 class="sicoob-pix-step-title"><?php _e('Escolha a opção PIX', 'sicoob-payment'); ?></h4>
                        <p class="sicoob-pix-step-text">
                            <?php _e('Procure pela opção "PIX" ou "Pagar com PIX" no menu principal.', 'sicoob-payment'); ?>
                        </p>
                    </div>
                </div>

                <div class="sicoob-pix-step">
                    <div class="sicoob-pix-step-number">3</div>
                    <div class="sicoob-pix-step-content">
                        <h4 class="sicoob-pix-step-title"><?php _e('Escaneie o QR Code', 'sicoob-payment'); ?></h4>
                        <p class="sicoob-pix-step-text">
                            <?php _e('Use a câmera do app para escanear o QR Code ou cole o código PIX.', 'sicoob-payment'); ?>
                        </p>
                    </div>
                </div>

                <div class="sicoob-pix-step">
                    <div class="sicoob-pix-step-number">4</div>
                    <div class="sicoob-pix-step-content">
                        <h4 class="sicoob-pix-step-title"><?php _e('Confirme o pagamento', 'sicoob-payment'); ?></h4>
                        <p class="sicoob-pix-step-text">
                            <?php _e('Verifique os dados e confirme o pagamento. O valor será debitado instantaneamente.', 'sicoob-payment'); ?>
                        </p>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

<!-- Bloco de Sucesso (inicialmente oculto) -->
<div class="sicoob-pix-success-block" id="sicoob-pix-success-block" style="<?= $is_paid ? 'display: block;' : 'display: none;' ?>">
    <div class="sicoob-pix-success-header">
        <h3><?php _e('Pagamento Recebido!', 'sicoob-payment'); ?></h3>
    </div>

    <div class="sicoob-pix-success-content">
        <div class="sicoob-pix-success-message">
            <div class="sicoob-pix-success-info">
                <p class="sicoob-pix-success-text">
                    <?php _e('Obrigado! Seu pagamento via PIX foi processado com sucesso.', 'sicoob-payment'); ?>
                </p>
                <p class="sicoob-pix-success-details">
                    <?php _e('Em breve, você receberá mais informações sobre seu pedido por e-mail.', 'sicoob-payment'); ?>
                </p>
            </div>
        </div>

        <div class="sicoob-pix-success-actions">
            <a href="<?php echo esc_url(wc_get_page_permalink('shop')); ?>" class="sicoob-pix-success-btn">
                <?php _e('Ver mais produtos', 'sicoob-payment'); ?>
            </a>
        </div>
    </div>
</div>
